apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: jupyterhub
  name: jupyterhub-img
spec:
  output:
    to:
      kind: ImageStreamTag
      name: jupyterhub-img:latest
  source:
    git:
      uri: https://github.com/wseaton/jupyterhub-odh.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jupyterhub:latest
    type: Source
  triggers:
  - type: ConfigChange
  - type: ImageChange
